import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/style.scss"
import WhatsAppFloat from "@/components/Common/WhatsAppFloat"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "JP FINSERV",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <WhatsAppFloat />
      </body>
    </html>
  )
}
